# Generated by Django 5.0.7 on 2024-07-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('matriculation_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
            ],
        ),
    ]
