# Generated by Django 5.0.7 on 2024-07-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$RAD7dcUDWp7EymCYALtegM$E2pD20zw3DCI0DsL3Qiv1Ywksmmc342ag7y7QOYi+fo=', max_length=128),
        ),
    ]
