# Generated by Django 5.0.7 on 2024-07-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$3Vpjs5UQXAWJ0CdLAgAt6w$RvXL4tfPOO1uFNb6oupD7PIwKwLFhngwDH8D12r8gYU=', max_length=128),
        ),
    ]
