# Generated by Django 5.0.7 on 2024-07-16 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='voted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='student',
            new_name='user',
        ),
    ]
