# Generated by Django 5.0.7 on 2024-07-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=10)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='candidate_photos/')),
            ],
        ),
    ]
